In [10]:
import numpy as np
import pandas as pd

In [12]:
movie_data = pd.read_csv("/content/IMDB-Movie-Data.csv")

In [13]:
print("Shape : ",movie_data.shape)

Shape :  (1000, 12)

In [14]:
movie_data.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [15]:
movie_data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [16]:
movie_data[movie_data.isna()]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
movie_data.duplicated()
movie_data.drop_duplicates()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [19]:
#5
movie_data = movie_data.rename(columns={"Title":"Movie_Title"})

In [20]:
#6
movie_data["Genre"].unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [21]:
#7

movie_data['Num_Genres'] = movie_data['Genre'].str.count(',') + 1
movie_data[['Movie_Title','Num_Genres']]

                 Movie_Title  Num_Genres
0    Guardians of the Galaxy           3
1                 Prometheus           3
2                      Split           2
3                       Sing           3
4              Suicide Squad           3
..                       ...         ...
995     Secret in Their Eyes           3
996          Hostel: Part II           1
997   Step Up 2: The Streets           3
998             Search Party           2
999               Nine Lives           3

[1000 rows x 2 columns]

In [22]:
#8
reve_mean = movie_data['Revenue (Millions)'].mean()
metascore_mean = movie_data['Metascore'].mean()
movie_data['Revenue (Millions)'] = movie_data['Revenue (Millions)'].fillna(reve_mean)
movie_data['Metascore'] = movie_data['Metascore'].fillna(metascore_mean)
movie_data.isnull().sum()

Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Num_Genres            0
dtype: int64

In [23]:
#9
movie_data.nlargest(5, 'Rating')[['Movie_Title', 'Rating']]

         Movie_Title  Rating
54   The Dark Knight     9.0
80         Inception     8.8
117           Dangal     8.8
36      Interstellar     8.6
96     Kimi no na wa     8.6

In [24]:
#10
highest_rev = movie_data.loc[movie_data['Revenue (Millions)'].idxmax()]
lowest_rev = movie_data.loc[movie_data['Revenue (Millions)'].idxmin()]
print("highest revevnue",highest_rev[['Movie_Title', 'Revenue (Millions)']])
print("lowest revevnue",lowest_rev[['Movie_Title', 'Revenue (Millions)']])

highest revevnue Movie_Title           Star Wars: Episode VII - The Force Awakens
Revenue (Millions)                                        936.63
Name: 50, dtype: object
lowest revevnue Movie_Title           A Kind of Murder
Revenue (Millions)                 0.0
Name: 231, dtype: object

In [25]:
#11
movie_data.groupby('Director')['Rating'].mean().sort_values(ascending=False)

Director
Nitesh Tiwari                       8.80
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Florian Henckel von Donnersmarck    8.50
                                    ...
Micheal Bafaro                      3.50
Jonathan Holbrook                   3.20
Shawn Burkett                       2.70
James Wong                          2.70
Jason Friedberg                     1.90
Name: Rating, Length: 644, dtype: float64

In [26]:
#12
movie_data['Year'].value_counts().sort_index()

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

In [27]:
#13
high_rated_high_revenue = movie_data[(movie_data['Rating'] > 8) & (movie_data['Revenue (Millions)'] > 100)]
high_rated_high_revenue[['Movie_Title', 'Rating', 'Revenue (Millions)']]

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

In [28]:
#14
movie_data.groupby('Director').agg(
    {'Rating': 'mean', 'Revenue (Millions)': 'mean'}
    ).sort_values(by='Rating', ascending=False)

                                  Rating  Revenue (Millions)
Director
Nitesh Tiwari                       8.80           11.150000
Christopher Nolan                   8.68          303.018000
Olivier Nakache                     8.60           13.180000
Makoto Shinkai                      8.60            4.680000
Florian Henckel von Donnersmarck    8.50           11.280000
...                                  ...                 ...
Micheal Bafaro                      3.50           82.956376
Jonathan Holbrook                   3.20           82.956376
Shawn Burkett                       2.70           82.956376
James Wong                          2.70            9.350000
Jason Friedberg                     1.90           14.170000

[644 rows x 2 columns]

In [29]:
#15
movie_data.groupby('Year').agg(
    {'Movie_Title': 'count', 'Rating': 'mean'}
    ).rename(columns={'Movie_Title': 'Movie_Count'})

      Movie_Count    Rating
Year
2006           44  7.125000
2007           53  7.133962
2008           52  6.784615
2009           51  6.960784
2010           60  6.826667
2011           63  6.838095
2012           64  6.925000
2013           91  6.812088
2014           98  6.837755
2015          127  6.602362
2016          297  6.436700

In [30]:
#16
movie_data['Profitability'] = movie_data['Revenue (Millions)'] / movie_data['Runtime (Minutes)']
movie_data.nlargest(10, 'Profitability')[['Movie_Title', 'Profitability']]

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [31]:
#17
def rating_group(rating):
    if rating >= 7.5:
        return 'Excellent'
    elif rating >= 6.0:
        return 'Average'
    else:
        return 'Poor'

movie_data['Rating_Category'] = movie_data['Rating'].apply(rating_group)
movie_data[['Movie_Title', 'Rating', 'Rating_Category']]

                 Movie_Title  Rating Rating_Category
0    Guardians of the Galaxy     8.1       Excellent
1                 Prometheus     7.0         Average
2                      Split     7.3         Average
3                       Sing     7.2         Average
4              Suicide Squad     6.2         Average
..                       ...     ...             ...
995     Secret in Their Eyes     6.2         Average
996          Hostel: Part II     5.5            Poor
997   Step Up 2: The Streets     6.2         Average
998             Search Party     5.6            Poor
999               Nine Lives     5.3            Poor

[1000 rows x 3 columns]

In [32]:
#18
def calculate_score(row):
    return (row['Rating'] * 10) + row['Revenue (Millions)']

movie_data['Score'] = movie_data.apply(calculate_score, axis=1)
movie_data[['Movie_Title', 'Rating', 'Revenue (Millions)', 'Score']].sort_values(by='Score', ascending=False)

,Movie_Title,Rating,Revenue (Millions),Score
50,Star Wars: Episode VII - The Force Awakens,8.1,936.63,1017.63
87,Avatar,7.8,760.51,838.51
85,Jurassic World,7.0,652.18,722.18
76,The Avengers,8.1,623.28,704.28
54,The Dark Knight,9.0,533.32,623.32
...,...,...,...,...
27,Dead Awake,4.7,0.01,47.01
936,The Human Centipede (First Sequence),4.4,0.18,44.18
237,The Disappointments Room,3.9,2.41,41.41
871,Dragonball Evolution,2.7,9.35,36.35
829,Disaster Movie,1.9,14.17,33.17